config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :employees, :leads, :skills
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_and_belongs_to_many :skills
  belongs_to :lead
  belongs_to :project
  validates :name, presence: true
end

app/models/lead.rb
class Lead < ApplicationRecord
	has_many :employees
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :employees
end

app/models/skill.rb
class Skill < ApplicationRecord
	validates :skill, presence:true
	has_and_belongs_to_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def new													
		@employee = Employee.new()
	end
	def index
		@employees = Employee.all 							
	end
	def create
		@employee = Employee.new(employee_params)
		@employee.save							
		redirect_to @employee
	end					
	def show
		@employee=Employee.find(params[:id])	
	end
	private
	def employee_params
		params.require(:employee).permit(:name,:project_id,:lead_id,:skill_ids => [])
	end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
def index
		@leads = Lead.all 							
	end
	def create
		@leads = Lead.new(lead_params)	
		@leads.save								
		redirect_to leads_path				
	end
	def show
		@lead=Lead.find(params[:id])
	end
	private
	def lead_params
    	params.require(:lead).permit(:lead_name, :employee_ids => [])
  	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
def new													
	end
	def index
		@skills = Skill.all 							
	end
	def create
	    @skill = Skill.new(skill_params)
	    @skill.save
	    redirect_to @skill
	end
	def show
		@skill=Skill.find(params[:id])	
	end
	private
	def skill_params
    	params.require(:skill).permit(:skill, :employee_ids => [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/index.html.erb
 <h1>List of employees</h1>
<ul>
  <% @employees.each do |employee| %>
    <li><a href="/employees/<%=employee[:id]%>"><%= employee.name %></li>
  <% end %>
</ul>

<%= link_to 'Create new Employee', new_employee_path %><br>
<p><%= link_to 'list of Leads', leads_path %></p>

app/views/employees/new.html.erb
<h1> Page to create New employee </h1>
<%= form_for :employee,url: employees_path  do |f| %>
  <p>
      <%= f.label :Employee_Name %><br>
      <%= f.text_field :name %>
  </p>
  <p>
      <%= f.label :Team_lead%><br>
      <%= f.collection_radio_buttons :lead_id, Lead.all, :id, :lead_name do |m| %>
        <%= m.radio_button %> <%= m.label %>
      <% end %>
  </p>

  <p>
    <%= f.label :Project%> <br>
    <%= f.collection_select :project_id, Project.order(:project),:id,:project, include_blank: true %>

  </p>
    <p>
      <%= f.label :Skills %><br>
      <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :skill do |m| %>
       <%= m.check_box %> <%= m.label %>
    <% end %>
  </p>
  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/employees/show.html.erb
<h1><%=@employee.name %> Details </h1>
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p> 
<p>
  <strong>Project:</strong>
  <%= @employee.project.project %>
</p>
<p>
  <strong>Skills:</strong>
  <% @employee.skills.each do |x| %>
  <%= x.skill %>
  <% end %>
</p>
<p>
  <strong>Lead:</strong>
  <%= @employee.lead.lead_name %>
</p>
<td><%= link_to 'Back to welcome page', welcome_index_path() %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leads/index.html.erb
<h1> list of leads</h1>

<ul>
  <% @leads.each do |lead| %>
      <li><a href="/leads/<%=lead[:id]%>"><%= lead.lead_name %></li>
  <% end %>
</ul>
<%= link_to 'Add new Lead', new_lead_path %>
<p><%= link_to 'list of employees', employees_path %></p>

app/views/leads/new.html.erb
<h1> Page to add new leads</h1>

<%= form_for :lead, url: leads_path do |f| %>
  <p>
      <%= f.label :lead_name %><br>
      <%= f.text_field :lead_name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/leads/show.html.erb
<p>
  <strong>Lead:</strong>
  <%= @lead.lead_name %>
</p>

<table>
  <tr>
    <th> Employee </th> <th> Skills </th>
  </tr>
  <% @sorted = @lead.employees.sort {|a,b| b.skills.count <=> a.skills.count} %>
  <% @sorted.each do |employee| %>
    <tr>
      <td> <%=employee.name %> </td> <td> <%= employee.skills.count %> </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create new Employee', new_employee_path %>
<p><%= link_to 'back to list', leads_path %></p>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Know your data base</p>
<%= link_to 'create_an_employee', new_employee_path%><br>
<%= link_to 'employee_list', employees_path%>